### ISSUE TITLE
Add Exxtension functions offer Get and PutRepositoryMapper

### ISSUE THREAD

**Issue by Atternatt** [mobilejazz/harmony-reference#10]
Hello I think it's interesting to add extension functions to create directly RepositoryMappers from DataSources. Something like this:
`
fun <In, Out> GetDataSource<In>.toGetRepository(mapper: Mapper<In, Out>): GetRepository<Out> = GetRepositoryMapper(toGetRepository(), mapper)`

so we can call it in code like this:

`datasource.toGetRepository(entityToBoMapper).toGetInteractor(executor)`

**Comment by joselufo** [comment]
I like the idea. You could also do it for the Put and Delete interfaces.

**Comment by Atternatt** [comment]
Yes, I've already made them, but I was just posting the question to ensure it was ok :P

**Comment by vilanovi** [comment]
In order to keep consistency and cohesion with our different layers, you shouldn't be able to jump within 1 method from a datasource to a repository mapper, as before you must specify which repository type you want.

The pipeline should be something like:

```
myDataSource.toGetRepository().withMapping(A2BMapper()).toGetInteractor(executor)
```

- `.toGetRepository()`: would return a SingleGetDataSourceRepository
- `.withMapping(A2BMapper())`: would compose a repository inside `GetRepositoryMapper`

Note that method names are just to give example, and that for a PutRepository you would need to pass 2 mappers in the parameters of the `withMapping` method.

**Comment by joselufo** [comment]
@vilanovi I don't really understand what is the issue? If you can overload the method `.toGetRepository(mapper)` with a mapper parameter and instead to give you a `SingleGetDataSourceRepository` is going to give you the `RepositoryMapper` configured with the `SingleGetDataSourceRepository` why not? if it's only an extension function. 

We could have another extension like  `toGetRepository(repository, mapper)` and it's going to wrap the repository provided in the RepositoryMapper with the mapper provided.

**Comment by Atternatt** [comment]
I actually understand the view point of @vilanovi . If we are used to follow a layer based path to create the end object then I'd make sense to add an extra step in the extension functions aswell. What I Propose is make both of them so we can jump from a DataSourvce into a repositoryMapper directly and also from a repository to a RepositoryMapper.

**Comment by vilanovi** [comment]
You are assuming you will always apply a mapping at a `SingleXXXDataSourceRepository`, which might not be correct. You can easily have a custom repo and wanting to do `myCustomRepository.withMapping(mappers...)`.

Then, and additionally if we all agree, we could have a method overload in the `toGetRepository` and make that if you pass a parameter, it builds a `SingleXXXDataSourceRepository` and combines it with a `XXXRepositoryMapper`. But this is an extra addition that might add extra complexity (magicness) and we need to ask the overall team what they think.

**Comment by vilanovi** [comment]
Also, I don't understand how you want to build the `toGetRepository(repository, mapper)` method. You pass as a parameter .. something that need to be initialized with the datasource which is the receiver of the method? :/

**Comment by Atternatt** [comment]
Indeed the receiver is the datasource

**Comment by vilanovi** [comment]
My overall point is: if we want to be able to build things using the dot notation in a single line, then let's do it. But let's keep some consistency: repositoryMappers act over repositories and not datasources.

Once this is done, we can have the custom methods marc was proposing.

I agree in both things.

**Comment by Atternatt** [comment]
So I'm ok to implement both at the end we are shortening thins. I think that if we add these functions into harmony docs everything should be fine.

**Comment by vilanovi** [comment]
Is there an agreement?

**Comment by joselufo** [comment]
I think this discussion is going crazy to something that it should be easier and we should close it as it generating differents branches in the harmony-kotlin core and this is something that it's not good. 

I'm happy to go with the @vilanovi  suggestion even when I'm not fully agree on. 

Maybe we can close it now and start the merges in the harmony-kotlin. @Atternatt are you ok with it?

**Comment by vilanovi** [comment]
1. I would not change the `toXXXRepository()` methods. These convert a datasource into a `SingleXXXDataSourceRepository` and work fine.
2. We could implement similar methods (extensions on DataSource and Repository) for mappings:

```
// Pseudocode
extension GetDataSource<T> {
   func map<K>(_ mapper: Mapper<T,K>) -> GetDataSource<K> {
      return GetDataSourceMapper(self, mapper)
   }
}

extension GetRepository<T> {
   func map<K>(_ mapper: Mapper<T,K>) -> GetRepository<K> {
      return GetRepositoryMapper(self, mapper)
   }
}
```
and use it somehow as:

```swift
let rawDataSource : GetDataSource<Data> = ...
let interactor =  rawDataSource.map(DataToUserMapper()).toGetRepository().toGetInteractor()
let interactor =  rawDataSource.toGetRepository().map(DataToUserMapper()).toGetInteractor()
```

What do you think?

**Comment by franmontiel** [comment]
I agree with Joan proposal. It is easy to understand. You always have "transformation" functions to the next possible objects in the pipeline.

**Comment by joselufo** [comment]
@vilanovi Regarding your second point:
The name `map` is not a good naming as it's the same one as the functional `map` function and it's not doing the same thing. 

I rather prefer to use the `.withMapping(mapper)` function proposed above.

**Comment by vilanovi** [comment]
@joselufo agreed.

Do we have a consensus? shall we agree on:

1. Implementing the `withMapping(EntityToModelMapper())` methods for `GetDataSource` and `GetRepository`.
2. Implementing the `withMapping(in: ModelToEntityMapper(), out: EntityToModelMapper())` methods for `PutDataSource` and `PutRepository.

Agreement?

**Comment by vilanovi** [comment]
ok, agreed. Will move forward with this.
