### ISSUE TITLE
Add proper exception for Network errors?

### ISSUE THREAD

**Issue by franmontiel** [mobilejazz/harmony-reference#12]
Hi, 
I have a doubt that might be useful to share publicly in case anyone else has it too.

Right now our CacheRepository handles two types of Exceptions: `DataNotFoundException` and `ObjectNotValidException`.

Imagine that in an app I need a custom `NetworkException` to notify the end users about the details of the error. In here we have two options:

- Should we make our custom exception inherit from DataNotFoundException?

- Or should we add a generic NetworkException for failures to the core and use that one?

I think the first option is the good one but I want to know your opinion on this.

**Comment by vilanovi** [comment]
I already thought about this some time ago and I was thinking the first option as the best one.

**Comment by RubenVot** [comment]
I think I agree with you because the mission of the repository is to find objects, if there is a network issue (or whichever other issue) the result is still that Data was Not Found.

**Comment by franmontiel** [comment]
Thanks for your responses. It is pretty clear now. 
**Summing up:**
Any custom Exception that we need our DataSources to throw should inherit from `DataNotFoundException` (or the iOS equivalent)
