### ISSUE TITLE
Make DeleteDatasource/DeleteRepository/DeleteInteractror use generic Types

### ISSUE THREAD

**Issue by franmontiel** [mobilejazz/harmony-reference#13]
Right now they are not generic as we don't need those classes to be generic as they don't take any argument different from Query and don't return anything. 
But taking into account Dependency Injection will be very useful to make them generic so there is no conflict between injections. Here an example:

- I configure DI to inject two DeleteDatasources (one for `Model1` and the other for `Model2`).
- There is a clash as now we have the same class provided twice.
- In Android we can solve this using `@Named` annotation or creating qualifiers to differentiate them. 
  - This is an extra work that won't be required if I configure `DeleteDataSource<Model1>` and `DeleteDataSource<Model2>`
- ~~But real the problem arises when I want to create a Generic dependency injection configuration module and in this case I cannot rely on the previously mentioned methods~~.
  - ~~By the way the idea behind this generic module is to have a base `Module<T>` to be extended by the `Module<Model1>` and that will have all the common pipeline already configured. This will make much easier to configure dependency injection on each Model.~~ <- (ignore this is not doable)

**Comment by RubenVot** [comment]
My first thought is that this is a DI problem which shouldn't be translated into Harmony. 

However, thinking a bit more, I see that making the DeleteDatasources generics might clear the sintax for non DI projects as well. 

My vote is YES 
https://media.giphy.com/media/8Fxlp25ov2RCGwye9I/giphy.gif

**Comment by vilanovi** [comment]
My first thought is the same as Rubén: a DI problem shouldn't be a reason to modify the base architecture Harmony, even more, if the issue requires to add some generics in a class that doesn't require them.

However, my second thought is the same. I don't think we should translate this issue into adding a generic type T into the DataSource.

*NOTE*: In Harmony-Swift, the `DeleteDataSource` and `DeleteRepository` doesn't have generics (as in Kotlin). However, the `DeleteInteractor` does. This is a misalignment with the base Harmony reference (https://github.com/mobilejazz/harmony-reference/blob/master/Interactor/Interactor.md). Note this issue in Harmony-Swift is actually resolving the DI problem as you propose here (even if it only applies to Interactors). Therefore, we need to take action somehow:

a) By modifying Harmony-Swift and removing the generic type T in delete interactors.
b) By modifying the Harmony specification and adding a generic type T in delete interactors only (and applying changes in Kotlin and other implementations but Swift).
c) By modifying the Harmony specification and adding a generic type T in delete interactors, delete repositories and delete data sources (and applying changes in all Harmony implementations).

Waiting for your thoughts.

**Comment by lucianosantana** [comment]
I'd prefer to keep it simple and do not use the generic type in the Delete flow.
We won't really use the generic for type checking or some generic logic. In this case it would be acting as a metadata, which in my opinion is not the purpose of generics.

**Comment by vilanovi** [comment]
I agree Luciano!

**Comment by joselufo** [comment]
Agree with @lucianosantana, we shouldn't modify our base code just to satisfy a DI issue. 

Regarding Swift having a generic type in the Delete interactor, I would say that we should go with the option **A** to avoid misalignment in with the base architecture.

**Comment by vilanovi** [comment]
Yes, definitely, once we confirm the agreement (I think we mostly have, right?) I'll open an issue in harmony-swift and remove the genercis from the delete interactors.

**Comment by franmontiel** [comment]
If maintaining 1:1 behavior on harmony in all platforms is a top priority and this problem does not affect all platforms I agree on keeping it as it is without generics.

If we want to allow some differences between platforms this change can make our life easier with no significant drawbacks (at least not one of I can think of at this moment).

**Comment by vilanovi** [comment]
so decision: **NO GENERICS IN DELETE DATASOURCE/REPOSITORY/INTERACTORS**

Will fix swift and remove the generics on the interactors.
