### ISSUE TITLE
Match Logger log level types with Bugfender log level types

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-reference#15]
Currently, `Logger`has the log level types:

- info
- warning
- error

However, Bugfender has the log level types:

- info
- error
- fatal

There is no correct 1-to-1 match between these log levels and my proposition is to modify the log level types of `Logger` to match the same as in Bugfender: remove `warning` and add `fatal`.

Thoughts?

**Comment by franmontiel** [comment]
For me it's fine. In the case of Android we have a couple more of supported logs levels that I think we should still give support in there. 

By the way Logger interface in Android currently is outside the harmony library. I think it makes sense to add it to the library and then be able to change the API if is needed.

**Comment by joselufo** [comment]
Bugfender right now supports the following log levels:
- Debug (D)
- Warning (W)
- Error (E)
- Trace (T)
- Info (I)
- Fatal(F)

I highly recommend using the same ones as they are the standard.

**Comment by RubenVot** [comment]
+1 to use the same than BF

**Comment by vilanovi** [comment]
I agree, let's make it this way then. Agreement?

**Comment by lucianosantana** [comment]
There is no single standard for log levels. There are some levels that are quite common, such as _Error_, _Warning_, _Info_. Bugfender uses some sort of extended standard, similar to [Apache Log4J](https://logging.apache.org/log4j/2.x/manual/customloglevels.html). I agree with @joselufo 's suggestion of using it. But we must be aware that depending on the framework / library some of those levels doesn't even exist (for example, _Fatal_) and we should map it some way (for instance, _Fatal_ level could be mapped to _Error_).

**Comment by newboadki** [comment]
Happy with the change.

**Comment by doup** [comment]
I'm not fully happy of BF dictating how the Harmony logger should behave, but the alternative (no being compatible with BF) is worse. So, +1 on adding the same log levels and a `keyValue` method.

**Comment by joselufo** [comment]
I think with the proposal public contract of the `Logger` we can solve most of the cases in all the languages / platforms. 

So if everyone agree on we can move fordward no?

**Comment by vilanovi** [comment]
Waiting for typescript implementation to be merged and updated the reference. Then, we will create tasks for other platforms to follow the same structure.

**Comment by vilanovi** [comment]
Newer Logger implementation at https://github.com/mobilejazz/harmony-typescript/pull/5.

All other platforms must follow the same example.
