### ISSUE TITLE
MainOperation should be removed in favor of DefaultOperation?

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-reference#4]
In the new `CacheRepository` we have a `MainOperation`, which by definition forwards the query to the "main data source" without doing anything else.

In DataSources, we try to keep queries as much generic and decoupled from the data source implementation as possible (because a same query must be supported by many DataSource implementations). Same approach should be used with operations and repositories.

For example, if we require that ALL REPOSITORIES support the `DefaultOperation`, then we can easily switch from one repo to another one in the dependency injection graph. Right now, this can't be done on the CacheRepository, as it requires the `MainOperation` instead.

Therefore, my proposal is:

1. Remove the `MainOperation` and use the `DefaultOperation` instead inside the `CacheRepository`.
2. All repositories must accept the "DefaultOperation".
3. Reuse operation types as much as possible among Repository implementations (aka. Operation names must be generic enough) (same as we do with queries).

Let me know your thoughts.

**Comment by joselufo** [comment]
I like the idea as we could be more dynamic switching between repositories and we don't need to think or check if the repository is compatible with your datasource or interactor. 

Why not deleting DefaultOperation and keep the MainOperation as the main one? I like more the name now of Main rather than Default.

**Comment by vilanovi** [comment]
Ok for me!

**Comment by newboadki** [comment]
If we force all repositories to accept MainOperation, what happens if a repository does not have the concept of a main data source? What if a repository aggregates the contents of several data sources, without defining a main data source? I think me mean DefaultOperation, but we need to find a more descriptive name.

**Comment by vilanovi** [comment]
I think this time I need to agree with @newboadki. It's better to keep a more generic name like `DefaultOperation` and every repository must accept it and perform what it thinks that is a "Default" behavior.

Returning to the `CacheRepository`, I have now an idea:

**Option A** 
Just replace the `MainOperation` for the `DefaultOperation`.  By doing this, if a user uses the `CacheRepository` it would be just forwarding everything to the main data source. No cache would be applied.

**Option B)**
 We could define that the `DefaultOperation` is actually none of the already 4 operations (aka. is not the `MainOperation`) and implement a custom behavior:

- **GET**: behave like a `CacheSyncOperation` (use the cache first if available).
- **PUT** & **DELETE**: behave like a `MainSyncOperation` (apply changes to the main first, then update cache).

This way, by supporting the `DefaultOperation` we could implement what it is supposed to be a "default" behavior on each repository. Imagine this situation where you have interactors on the UI using the `DefaultOperation` and you replace the `SingleDataSourceRepository` for a `CacheRepository`. Without having to modify the UI you would suddently be using the cache.

**Comment by RubenVot** [comment]
Just commenting to let you know that I read the thread but I´m a bit newbie so I don´t want to add to much noise. `DefaultOperation` and Option B sounds good to me.

**Comment by joselufo** [comment]
My vote goes to the **Option A**

**Comment by franmontiel** [comment]
I think I'm inclined for B but I have no strong feelings about this.

For me makes sense that the default operation of a CacheRepository is to use the cache.

**Comment by vilanovi** [comment]
I have to agree with @franmontiel. If this is a Cache repository, let the default be the cache. Otherwise, by DI, we could inject a `SingleDataSourceRepository` and use the main one.

**Comment by joselufo** [comment]
Makes sense, let's approve it with the Option A.

**Comment by vilanovi** [comment]
WTF @joselufo , we were discussing to do option B.

**Comment by vilanovi** [comment]
Great! decision is taken.
