### ISSUE TITLE
Homogenize repositories description, URL and tags to improve discoverability in Github

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-reference#40]
**DESCRIPTION**
Add short description for each platform, this is what we have right now:

- `Building blocks for TypeScript applications based on Harmony concept`
- `Harmony Kotlin code`
- `Mobile Jazz Swift toolkit utilities`
- `Harmony PHP library`

To decide:

1. Is it a `concept`, `code`, `toolkit`, `library` or another thing?
2. Decide a template phrase

**TAGS**
Tags we have on TS repository:

- `clean-architecture`
- `typescript`
- `angular`
- `nestjs`

To decide:

3. What tags should have minimum: `clean-architecture` + `[platform]` ...

**WEBSITE**
I've updated the website for TS, Kotlin & Swift, @Alex-DA you should update PHP as I don't have access.

**Comment by joselufo** [comment]
Thanks for taking care of checking these things and propose the changes. 

I think it's something that we could just discuss today in our meeting and decide the template.

**Comment by doup** [comment]
- Harmony Reference defines **standard**
- The implementations should be called **framework**
- Tags to use:
  - mandatory: `clean-code`, `clean-architecture`
  - plus language/platform related tags, e.g. for TS: `TypeScript`, `Angular`, `NestJS`...
