### ISSUE TITLE
Should we change the static-generator to Docusaurus?

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-reference#42]
I've tested [Docusaurus](https://v2.docusaurus.io) and it can do quite a lot out of the box. Migrating to Docusaurus would fix the following issues:

- :white_check_mark: Add search functionality (#18), using [Algolia DocSearch]( https://docsearch.algolia.com) or other provider.
- :white_check_mark: Show tabbed code snippets (#19).
- :white_check_mark: Add edit this page link (#20).

Other advantages:

- Multi-level sidebar menu for better content organization
- Per page TOC and headers with links (with the typical `#`)
- Easily add non-documentation pages, e.g.: customized index, blog…
- 100% JS tooling. It should be easier for us to tweak the site.

Disadvantages:

- It uses React for the templates and we might not be too familiar with it.
  - Or it could be seen as an opportunity to learn React a little… :P
- V2 of Docusaurus is still on Alpha (although is `alpha.43`). This one is also minor, as it looks like it's due Beta soon and it's already been used on production by other companies.

What do you think?

**Comment by doup** [comment]
Some examples, btw:

- https://v2.docusaurus.io
- https://vector.dev
- https://uniforms.tools

**Comment by vilanovi** [comment]
Looks super nice @doup , a pity we haven't discovered this before.

Question: How fast can we transition from what we have now? Could you estimate the transition?

**Comment by joselufo** [comment]
The same as Joan, pity that we haven't discovered this before.

**Comment by jfilowk** [comment]
Docusaurus would help a lot with the new reference organization that I'm going to show this Friday.
The current side menu only allows one submenu, if we want to have more than one level we need to implement it. Here is a screenshot with Docusaurus:
![image](https://user-images.githubusercontent.com/4893898/75361363-7ac1c480-58b7-11ea-8e41-77ab52b8630b.png)

The new organization is more specific for each concept so if we have tabs almost every page would be a single page (no scroll). It's much better to read and to find something.

Also, it would be great to have like a box for a 'good practice or tips or alert' so it's easy to find them. Now they are lost in the middle of the text.
![image](https://user-images.githubusercontent.com/4893898/75362135-97123100-58b8-11ea-87c2-2c2b1fd537bf.png)

**Comment by doup** [comment]
- We have around 50 code tabs in 32 documents.
- For the markdowns migration I think **around 2-3 hours** should be enough. The main work is to add the code tabs, change file names and update the menu.
- Then for the design we can keep it to the minimum in the beginning, I already have removed most of the default homepage elements and just kept the `Harmony Reference` title and `Get Started` button. The work would be to change the logo and footer + other tweeks if needed. **This would take 1-2h**.
- Lastly, it's the deployment, which should be very different from the current setup, but that's something for Jose.

So yeah, for a dirty first version keeping the current docs structure and with a super minimal vanilla design around 4 hours (tops).

Design would end up something like this, but with changed footer & logo:

![image](https://user-images.githubusercontent.com/188612/75523670-bd48e580-5a0c-11ea-85cd-21d6fd6905cd.png)

**Comment by doup** [comment]
Merged and published! 🎉 🎉
