### ISSUE TITLE
Adding delays to our data sources to make evident screen flaws in loading states

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-reference#7]
I often see poorly implemented application states while loading data. In some of our projects, I see many blank screens, wrongly placed loading indicators, and other flaws that only happen "while loading". 

As a way to debug this, I have spent some minutes and created a `DelayDataSource` class that forwards queries to a main data source but adds a delay once futures are resolved.

You can find the link to the pull request here: https://github.com/mobilejazz/harmony-ios/pull/8

The sample project of Harmony iOS is now using the DelayDataSource and we can easily see these delays happening.

The goal is to include this class as a resource in the Harmony reference library and use it to debug our code and make more visible the "loading state" of our views.

Let me know your thoughts on it.

**Comment by vilanovi** [comment]
--> Note that I would like to start using this to validate UI in PeerWell both iOS and Android.

**Comment by vilanovi** [comment]
Idea: make the delay infinite until a user-triggered event happens like volume-up or device-shake. This way we can get to do a long interaction with the user interface in a loading state (and try to trigger a pull-to-request, which is meaningless at this phase or see if we can cause any crash by manipulating the app).

**Comment by joselufo** [comment]
I like the idea but I would say that instead to only implement a custom delay datasource, I would abstract it a bit more and be more generic to be more useful for debugging in all platforms (including web)

If we implement a DebugDataSource class with the following features:
- **Delay**  configured as you described before.  
- **Error-Prone** we could configure a percentage of error that we want to achieve. For example, 3% of the actions should fail. We could identify raise conditions. 

Having these two features in a datasource we could have better testing. 

What do you think about this approach?

**Comment by vilanovi** [comment]
@joselufo this is a great idea! and now that is a generic debug tool, we can add new debug features:

- Delay configured as you described before.
- Error-Prone we could configure a percentage of error that we want to achieve. For example, 3% of the actions should fail. We could identify raise conditions.
- Log all queries and their results
- Measure (and log the results somehow) execution times lengths.

Great!

**Comment by joselufo** [comment]
We could start implementing the DebugDataSource with those features and we could add more features in the future if needed.

**Comment by vilanovi** [comment]
Great! Deal. I have it started on iOS. We can review there the progress.
